dist: trusty

language: node_js

node_js:
  - "6"
  - "8"

script:
  - if [ "$TRAVIS_NODE_VERSION" = "6" ]; then npm run test; fi
  - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then npm run test:coverage; fi
